[package]
name = "actix"
version = "0.1.0"
authors = ["finkrer <finkrer@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
actix-web = { version = "2.0.0", features = ["rustls"] }
rustls = "0.16.0"
