version: '3.7'

services:
  actix:
    image: actix:latest
    container_name: actix
    working_dir: /usr/src/actix
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./static:/usr/src/actix/static
      - ./templates:/usr/src/actix/templates
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped